In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory



In [33]:
import os
for dirname, _, filenames in os.walk('/content/16p-Mapping.txt'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [53]:
train = pd.read_csv('/content/16P.csv',encoding = 'unicode_escape')
train = train.dropna()

In [54]:
train.head()


Response Id  You regularly make new friends.  \
0            0                                0   
1            1                                0   
2            2                                0   
3            3                                0   
4            4                                0   

   You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                  0                                            
1                                                  0                                            
2                                                  0                                            
3                                                 -1                                            
4                                                  0                                            

   Seeing other people cry can easily make you feel like you want to cry too  \
0                                                  0                           
1                                                 -2                           
2                                                  2                           
3                                                  3                           
4                                                 -1                           

   You often make a backup plan for a backup plan.  \
0                                                0   
1                                               -3   
2                                                0   
3                                               -1   
4                                                0   

   You usually stay calm, even under a lot of pressure  \
0                                                  0     
1                                                 -1     
2                                                 -1     
3                                                  0     
4                                                  2     

   At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know  \
0                                                  1                                                                   
1                                                  2                                                                   
2                                                  2                                                                   
3                                                  0                                                                   
4                                                 -1                                                                   

   You prefer to completely finish one project before starting another.  \
0                                                  1                      
1                                                 -2                      
2                                                  0                      
3                                                 -2                      
4                                                 -2                      

   You are very sentimental.  \
0                          0   
1                          0   
2                          0   
3                          0   
4                          0   

   You like to use organizing tools like schedules and lists.  ...  \
0                                                  0           ...   
1                                                  3           ...   
2                                                  1           ...   
3                                                 -2           ...   
4                                                  1           ...   

   You believe that pondering abstract philosophical questions is a waste of time.  \
0                                                0.0                                 


In [55]:
train.shape

(42067, 62)

In [56]:
train.groupby('Personality')['Response Id']

In [57]:
train.groupby('Personality')['Response Id'].count()

Personality
ENFJ    2616
ENFP    2623
ENTJ    2633
ENTP    2633
ESFJ    2624
ESFP    2663
ESTJ    2629
ESTP    2630
INFJ    2636
INFP    2595
INTJ    2649
INTP    2673
ISFJ    2622
ISFP    2628
ISTJ    2561
ISTP    2652
Name: Response Id, dtype: int64

In [58]:
# Extraverted (E) / Introverted (I)
# Intuitive (N) / Sensing (S)
# Feeling (F) / Thinking (T)
# Judging (J) / Perceiving (P)

In [59]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier

In [60]:
# we define k-fold Cross-validation with 5 folds
number_folds = 2
kf = KFold(n_splits=number_folds, shuffle=True, random_state=1337)

In [61]:
from sklearn.preprocessing import StandardScaler

In [62]:
X = train.drop(['Response Id', 'Personality'], axis = 1)
y = train['Personality']

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.exceptions import ConvergenceWarning


In [64]:
import warnings
# Ignore convergence warnings for simplicity
warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [65]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [67]:

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



In [68]:
# Create and train the Logistic Regression model with L1 regularization
log_reg_l1 = LogisticRegression(penalty='l1', solver='liblinear', C=1.0)
log_reg_l1.fit(X_train, y_train)



LogisticRegression(penalty='l1', solver='liblinear')

In [69]:
# Make predictions on the test set
y_pred = log_reg_l1.predict(X_test)



In [70]:
# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)



In [72]:
# Print the results
print(f"Accuracy: {accuracy}")




Accuracy: 0.9104666825132716


In [73]:
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[712   5   2   1   5   1   0   1   2   5   2   5   8   1   0   5]
 [  3 711   3   4   9   3   1   1   3   0   3   5   4   2   2   1]
 [  0   3 755   0   3   1   4   1   1   6   4   1   1   6   4   2]
 [  7   3   5 729   3   1   7   3   1   1   0   2   3   6   2   0]
 [ 17   9   4   5 669  10  17  16  21   3  19  15   4   7  10   7]
 [  3   1   2   0   1 782   6   3   1   2   0   8   6   3   2   2]
 [  0   3   0   1   3   3 768   2   2   6   2  10  11   2   3   0]
 [  1   3   3   2  12   4   1 755   2   5   5   2   2   1   1   1]
 [  3   3   0   3  13   3   2   7 748   0   1  10   2  16   4   1]
 [ 11   2  11   2   8   1   9   5   6 702   8   1  20   2   6   2]
 [  6   2   2   0  11   3   5   5   0   5 700   4  17   5  14   3]
 [  4   4   1   2   7   5   3   2   3   4   9 685   1   3   4   3]
 [  1   5   4   3   1   1  16   5   9  10  13   7 677   5   3  14]
 [  0  10   5   6   3   3   4   2   9  10  13   4   1 726   3  11]
 [  5   2   6   1  11   5   0   3   4   8   

In [74]:
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

        ENFJ       0.92      0.94      0.93       755
        ENFP       0.93      0.94      0.93       755
        ENTJ       0.94      0.95      0.94       792
        ENTP       0.95      0.94      0.95       773
        ESFJ       0.88      0.80      0.84       833
        ESFP       0.94      0.95      0.95       822
        ESTJ       0.91      0.94      0.93       816
        ESTP       0.93      0.94      0.94       800
        INFJ       0.92      0.92      0.92       816
        INFP       0.91      0.88      0.89       796
        INTJ       0.88      0.90      0.89       782
        INTP       0.88      0.93      0.90       740
        ISFJ       0.87      0.87      0.87       774
        ISFP       0.90      0.90      0.90       810
        ISTJ       0.91      0.86      0.89       757
        ISTP       0.91      0.90      0.90       800

    accuracy                           0.91     12621
   

In [76]:
# Print the coefficients to see which features are selected
print("Coefficients:")
print(log_reg_l1.coef_)


Coefficients:
[[-3.85156446e-02  2.71642085e-02 -1.73986105e-01  8.95157078e-01
  -9.75327959e-03 -1.00735969e+00 -2.90712712e-01  3.97306333e-02
  -1.27555255e-01  3.81260841e-03  1.18964139e-01  2.58602778e-02
   1.24598732e+00  9.21958301e-01 -8.21839540e-01 -6.57020444e-01
  -3.95353657e-02 -4.08934621e-01  3.61445997e-01  1.09445732e+00
  -4.66532188e-02  1.41358317e-01  1.77850725e-02 -6.02809337e-02
   3.80195535e-01  6.91774514e-01 -9.04502871e-01 -9.02307068e-02
   6.93991314e-02  5.67471956e-01  1.64019877e-01  3.21971118e-02
   1.22673796e+00  0.00000000e+00  7.75841677e-01 -1.07554814e+00
   1.55231158e-01  1.46078880e-01  5.06335196e-01  3.28306694e-01
  -1.03161890e+00  6.48185149e-02 -3.87414507e-01  7.47711423e-01
  -1.17100189e-01 -4.49866207e-02  8.08189253e-02  1.20680216e-03
  -1.02029695e+00  5.48056570e-03  5.40141923e-02  4.89319779e-02
  -1.24399857e+00  1.62042524e-02  1.16618538e-01  2.13163068e-02
  -8.72405410e-02 -1.13196437e-01  1.99048368e-01  2.94486052e

In [77]:

# Print the feature names for better understanding
imp_df = pd.DataFrame()
imp_df['features'] = X.columns
imp_df['Coeff'] = log_reg_l1.coef_[0]
imp_df['Abs Coeff'] = abs(log_reg_l1.coef_[0])
imp_df['Perc Coeff'] = imp_df['Abs Coeff']/imp_df['Abs Coeff'].sum()
imp_df = imp_df.sort_values(by = 'Perc Coeff', ascending = False)
imp_df['CumSum Perc Coeff'] = imp_df['Perc Coeff'].cumsum()
imp_df

features     Coeff  Abs Coeff  \
12  You are more inclined to follow your head than...  1.245987   1.245987   
52  You feel more drawn to places with busy, bustl... -1.243999   1.243999   
32  You find it easy to empathize with a person wh...  1.226738   1.226738   
19  You are prone to worrying that things will tak...  1.094457   1.094457   
35  After a long and exhausting week, a lively soc... -1.075548   1.075548   
40                      You avoid making phone calls. -1.031619   1.031619   
48  Your personal work style is closer to spontane... -1.020297   1.020297   
5   At social events, you rarely try to introduce ... -1.007360   1.007360   
13  You usually prefer just doing what you feel li...  0.921958   0.921958   
26                 Your mood can change very quickly. -0.904503   0.904503   
3     You often make a backup plan for a backup plan.  0.895157   0.895157   
14  You rarely worry about whether you make a good... -0.821840   0.821840   
34  You rarely second-guess the choices that you h...  0.775842   0.775842   
43  If your plans are interrupted, your top priori...  0.747711   0.747711   
25   You tend to avoid drawing attention to yourself.  0.691775   0.691775   
15       You enjoy participating in group activities. -0.657020   0.657020   
29  You have always been fascinated by the questio...  0.567472   0.567472   
38        You like to have a to-do list for each day.  0.506335   0.506335   
17  Your happiness comes more from helping others ... -0.408935   0.408935   
42  In your social circle, you are often the one w... -0.387415   0.387415   
24                   You enjoy watching people argue.  0.380196   0.380196   
18  You are interested in so many things that you ...  0.361446   0.361446   
39                          You rarely feel insecure.  0.328307   0.328307   
59  You feel confident that things will work out f...  0.294486   0.294486   
6   You prefer to completely finish one project be... -0.290713   0.290713   
58                       You struggle with deadlines.  0.199048   0.199048   
2   Seeing other people cry can easily make you fe... -0.173986   0.173986   
30  You usually prefer to be around others rather ...  0.164020   0.164020   
36                    You enjoy going to art museums.  0.155231   0.155231   
37  You often have a hard time understanding other...  0.146079   0.146079   
21  You are definitely not an artistic type of per...  0.141358   0.141358   
8   You like to use organizing tools like schedule... -0.127555   0.127555   
10  You feel comfortable just walking up to someon...  0.118964   0.118964   
44  You are still bothered by mistakes that you ma... -0.117100   0.117100   
54                        You often feel overwhelmed.  0.116619   0.116619   
57  You would pass along a good opportunity if you... -0.113196   0.113196   
27  You lose patience with people who are not as e... -0.090231   0.090231   
56  You are very intrigued by things labeled as co... -0.087241   0.087241   
46  Your emotions control you more than you contro...  0.080819   0.080819   
28  You often end up doing things at the last poss...  0.069399   0.069399   
41  You often spend a lot of time trying to unders...  0.064819   0.064819   
23  You prefer to do your chores before allowing y... -0.060281   0.060281   
50  You would love a job that requires you to work...  0.054014   0.054014   
51  You believe that pondering abstract philosophi...  0.048932   0.048932   
20      You avoid leadership roles in group settings. -0.046653   0.046653   
45  You rarely contemplate the reasons for human e... -0.044987   0.044987   
7                           You are very sentimental.  0.039731   0.039731   
16  You like books and movies that make you come u... -0.039535   0.039535   
0                     You regularly make new friends. -0.038516   0.038516   
31  You become bored or lose interest when the dis...  0.032197   0.032197   
1   You spend a lot of your free time exploring va...  0.027164   0

In [78]:
imp_df.to_csv('/content/16P.csv', index = None)

In [79]:
len(train) ** 0.5

205.10241344265066

In [80]:
neighbor_settings = list(range(1, 25))
#neighbor_settings = [x for pair in zip(neighbor_settings, reversed(neighbor_settings)) for x in pair]
#neighbor_settings = neighbor_settings[:len(neighbor_settings)]  # In case the original list length is odd

In [81]:
final_training = pd.DataFrame()
final_test = pd.DataFrame()


In [ ]:
for n_neighbors in neighbor_settings:
    print(f"Neighbors: {n_neighbors}")

    training_accuracy = []
    test_accuracy = []

    fold = 0

    for train_index, test_index in kf.split(X, y):
        print(f"Fold: {fold}")
        X_train, X_test = X.loc[train_index], X.loc[test_index]
        y_train, y_test = y.loc[train_index], y.loc[test_index]

        clf = KNeighborsClassifier(n_neighbors=n_neighbors)  # build the model
        clf.fit(X_train, y_train)

        train_acc = clf.score(X_train, y_train)
        test_acc = clf.score(X_test, y_test)

        print([train_acc, test_acc])

        training_accuracy.append(train_acc) # record training set accuracy
        test_accuracy.append(test_acc)   # record generalization accuracy

        fold += 1


    final_training[n_neighbors] = training_accuracy
    final_test[n_neighbors] = test_accuracy

Neighbors: 1
Fold: 0
[1.0, 0.9756109156603594]
Fold: 1
[1.0, 0.9782722388627395]
Neighbors: 2
Fold: 0
[0.9862121428231826, 0.9752305790624702]
Fold: 1
[0.9883521916896454, 0.9765606427994105]
Neighbors: 3
Fold: 0
[0.9894451576094708, 0.9877816867928116]
Fold: 1
[0.9896358277075211, 0.9883040935672515]
Neighbors: 4
Fold: 0
[0.9891123472638235, 0.9883046496149092]
Fold: 1
[0.9893030331843682, 0.9881614605619741]
Neighbors: 5
Fold: 0
[0.9896353349498407, 0.9888276124370068]
Fold: 1
[0.989588285632785, 0.989064802928731]
Neighbors: 6
Fold: 0
[0.9893976132743784, 0.9887800703622706]
Fold: 1
[0.9894456594085765, 0.9889697142585461]
Neighbors: 7
Fold: 0
[0.9895877906147482, 0.988922696586479]
Fold: 1
[0.9897309118569935, 0.9893500689392859]
Neighbors: 8
Fold: 0
[0.989254980269101, 0.9888751545117429]
Fold: 1
[0.9893981173338404, 0.9889697142585461]
Neighbors: 9
Fold: 0
[0.9894451576094708, 0.9890177807359514]
Fold: 1
[0.989588285632785, 0.9893500689392859]
Neighbors: 10
Fold: 0
[0.98935006893

In [ ]:
import matplotlib.pyplot as plt
plt.errorbar(neighbor_settings, lahat_training.T.mean(axis=1),
             yerr=lahat_training.T.std(axis=1)/2, label="training accuracy")
plt.errorbar(neighbor_settings, lahat_test.T.mean(axis=1),
             yerr=lahat_test.T.std(axis=1)/8, label="test accuracy")
plt.ylabel("Accuracy")
plt.xlabel("n_neighbors")
plt.legend()